# After changing this file, check it on:
#   http://lint.travis-ci.org/
language: python

matrix:
  include:
    - python: "2.6"
    - python: "2.7"
      env:
        - TESTMODE=full
    - python: "3.2"
    - python: "3.3"
    - python: "3.4"
      env:
        - TESTMODE=full

before_install:
  - uname -a
  - free -m
  - df -h
  - python -V
  - pip -V
  - travis_retry sudo apt-get update -qq

install:
  - pip install --upgrade pip setuptools  # Upgrade pip and setuptools to get ones with `wheel` support

  # pip Scipy/Numpy versions take too long, use astropy wheels
  - sudo apt-get install libblas-dev libatlas-dev liblapack-dev
  - pip install --no-index --find-links http://wheels2.astropy.org/ numpy --trusted-host
  - pip install --no-index --find-links http://wheels2.astropy.org/ scipy --trusted-host

  - if [ "${TESTMODE}" == "full" ]; then pip install coveralls; fi;
  - python setup.py install

script:
  # Test installing with pip
  - pip install .

  # check we can import pypore
  - pushd /
  - echo "import pypore" | python
  - popd

  # Build C extensions next to .c files
  - python setup.py build_ext --inplace

  # run the tests
  - if [ "${TESTMODE}" == "full" ]; then
      coverage run --source=pypore setup.py test;
    else
      nosetests;
    fi;

after_success:
  - if [ "${TESTMODE}" == "full" ]; then coveralls; fi;

notifications:
  email: false
